name: Device problem report
description: Data points or functionalities are missing
title: "[Device problem]: "
labels: [device problem]
body: 
  - type: markdown
    attributes:
      value: |
        **IMPORTANT:** Before submitting:
        - You read the [FAQ](https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/blob/main/docs/EN/EN_faq.md)        
  - type: input
    id: link
    attributes:
      label: Link
      description: Link of this device from [Zigbee2MQTT](https://www.zigbee2mqtt.io/supported-devices/)
      placeholder: https://www.zigbee2mqtt.io/devices/TS130F_dual.html
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Adapter version
      placeholder: 2.3.0
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: What is missing or not working
      placeholder: I would have expected the or the data point has no function ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Device exposes
      description: You can get this information via the adapter, [How to do this](https://github.com/o0shojo0o/ioBroker.zigbee2mqtt/blob/main/docs/EN/EN_faq.md#how-do-i-get-the-exposes-from-a-device-).
      render: JSON
    validations:
      required: true
